server.port=4000

spring.application.name=keypilot-gateway



# Key storage location ? defaults to ~/.gateway-cli/keys.json
# Override with: -Dgateway.storage.path=/custom/path/keys.json
gateway.storage.path=${user.home}/.cli/keys.json